/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { OracleAddrResolverI } from "../OracleAddrResolverI";

export class OracleAddrResolverI__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OracleAddrResolverI {
    return new Contract(address, _abi, signerOrProvider) as OracleAddrResolverI;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "getAddress",
    outputs: [
      {
        name: "_address",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
