/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { SolcChecker } from "../SolcChecker";

export class SolcChecker__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SolcChecker {
    return new Contract(address, _abi, signerOrProvider) as SolcChecker;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "x",
        type: "bytes",
      },
    ],
    name: "f",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
