/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from "..";
import { UsingProvable } from "../UsingProvable";

export class UsingProvable__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<UsingProvable> {
    return super.deploy(overrides) as Promise<UsingProvable>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): UsingProvable {
    return super.attach(address) as UsingProvable;
  }
  connect(signer: Signer): UsingProvable__factory {
    return super.connect(signer) as UsingProvable__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UsingProvable {
    return new Contract(address, _abi, signerOrProvider) as UsingProvable;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_myid",
        type: "bytes32",
      },
      {
        name: "_result",
        type: "string",
      },
    ],
    name: "__callback",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_myid",
        type: "bytes32",
      },
      {
        name: "_result",
        type: "string",
      },
      {
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "__callback",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806327dc297e1461003b57806338bbfa50146100ea575b600080fd5b6100e86004803603604081101561005157600080fd5b8135919081019060408101602082013564010000000081111561007357600080fd5b82018360208201111561008557600080fd5b803590602001918460018302840111640100000000831117156100a757600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955061021e945050505050565b005b6100e86004803603606081101561010057600080fd5b8135919081019060408101602082013564010000000081111561012257600080fd5b82018360208201111561013457600080fd5b8035906020019184600183028401116401000000008311171561015657600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092959493602081019350359150506401000000008111156101a957600080fd5b8201836020820111156101bb57600080fd5b803590602001918460018302840111640100000000831117156101dd57600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955061023e945050505050565b60408051600081526020810190915261023a908390839061023e565b5050565b5050600080805260036020527f3617319a054d772f909f7c479a2cebe5066e836a939412e32403c99029b92eff555056fea165627a7a72305820c6449e5e33b16fd2b2327d02b7a6167869c2296ccb9a1c2e1e1bb347624e180e0029";
