/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ViaBond } from "../ViaBond";

export class ViaBond__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ViaBond {
    return new Contract(address, _abi, signerOrProvider) as ViaBond;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "txId",
        type: "bytes32",
      },
      {
        name: "result",
        type: "bytes16",
      },
      {
        name: "rtype",
        type: "bytes32",
      },
    ],
    name: "convert",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_symbol",
        type: "bytes32",
      },
      {
        name: "_forwarder",
        type: "address",
      },
      {
        name: "_sender",
        type: "address",
      },
      {
        name: "_receiver",
        type: "address",
      },
      {
        name: "_tokens",
        type: "uint256",
      },
    ],
    name: "transferForward",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "amount",
        type: "bytes16",
      },
      {
        name: "payer",
        type: "address",
      },
      {
        name: "currency",
        type: "bytes32",
      },
      {
        name: "cashContract",
        type: "address",
      },
    ],
    name: "requestIssue",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
