/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription,
} from ".";

interface BondInterface extends Interface {
  functions: {
    name: TypedFunctionDescription<{ encode([]: []): string }>;

    approve: TypedFunctionDescription<{
      encode([spender, tokens]: [string, BigNumberish]): string;
    }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    balances: TypedFunctionDescription<{ encode([]: [string]): string }>;

    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    issues: TypedFunctionDescription<{ encode([,]: [string, string]): string }>;

    purchases: TypedFunctionDescription<{
      encode([,]: [string, string]): string;
    }>;

    balanceOf: TypedFunctionDescription<{
      encode([tokenOwner]: [string]): string;
    }>;

    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    bondName: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;

    transfer: TypedFunctionDescription<{
      encode([receiver, tokens]: [string, BigNumberish]): string;
    }>;

    allowance: TypedFunctionDescription<{
      encode([tokenOwner, spender]: [string, string]): string;
    }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;

    initialize: TypedFunctionDescription<{
      encode([_name, _type, _owner, _oracle, _token]: [
        Arrayish,
        Arrayish,
        string,
        string,
        string
      ]): string;
    }>;

    transferForward: TypedFunctionDescription<{
      encode([_symbol, _forwarder, _sender, _receiver, _tokens]: [
        Arrayish,
        string,
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([owner, buyer, tokens]: [string, string, BigNumberish]): string;
    }>;

    requestIssue: TypedFunctionDescription<{
      encode([amount, payer, currency, cashContract]: [
        Arrayish,
        string,
        Arrayish,
        string
      ]): string;
    }>;

    convert: TypedFunctionDescription<{
      encode([txId, result, rtype]: [Arrayish, Arrayish, Arrayish]): string;
    }>;
  };

  events: {
    ViaBondIssued: TypedEventDescription<{
      encodeTopics([token, currency, value, price, tenure]: [
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    ViaBondRedeemed: TypedEventDescription<{
      encodeTopics([currency, value, price, tenure]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;

    Approval: TypedEventDescription<{
      encodeTopics([tokenOwner, spender, tokens]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    Transfer: TypedEventDescription<{
      encodeTopics([from, to, tokens]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;
  };
}

export class Bond extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Bond;
  attach(addressOrName: string): Bond;
  deployed(): Promise<Bond>;

  on(event: EventFilter | string, listener: Listener): Bond;
  once(event: EventFilter | string, listener: Listener): Bond;
  addListener(eventName: EventFilter | string, listener: Listener): Bond;
  removeAllListeners(eventName: EventFilter | string): Bond;
  removeListener(eventName: any, listener: Listener): Bond;

  interface: BondInterface;

  functions: {
    name(overrides?: TransactionOverrides): Promise<string>;

    "name()"(overrides?: TransactionOverrides): Promise<string>;

    approve(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    balances(arg0: string, overrides?: TransactionOverrides): Promise<string>;

    "balances(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    decimals(overrides?: TransactionOverrides): Promise<number>;

    "decimals()"(overrides?: TransactionOverrides): Promise<number>;

    issues(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<{
      parValue: string;
      price: string;
      purchasedIssueAmount: string;
      paidInAmount: string;
      paidInCurrency: string;
      timeIssuedOrSubscribed: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
    }>;

    "issues(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<{
      parValue: string;
      price: string;
      purchasedIssueAmount: string;
      paidInAmount: string;
      paidInCurrency: string;
      timeIssuedOrSubscribed: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
    }>;

    purchases(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<{
      parValue: string;
      price: string;
      purchasedIssueAmount: string;
      paidInAmount: string;
      paidInCurrency: string;
      timeIssuedOrSubscribed: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
    }>;

    "purchases(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<{
      parValue: string;
      price: string;
      purchasedIssueAmount: string;
      paidInAmount: string;
      paidInCurrency: string;
      timeIssuedOrSubscribed: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
    }>;

    balanceOf(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    "renounceOwnership()"(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    bondName(overrides?: TransactionOverrides): Promise<string>;

    "bondName()"(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: TransactionOverrides): Promise<boolean>;

    /**
     * Returns true if the caller is the current owner.
     */
    "isOwner()"(overrides?: TransactionOverrides): Promise<boolean>;

    symbol(overrides?: TransactionOverrides): Promise<string>;

    "symbol()"(overrides?: TransactionOverrides): Promise<string>;

    transfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    allowance(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    initialize(
      _name: Arrayish,
      _type: Arrayish,
      _owner: string,
      _oracle: string,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "initialize(bytes32,bytes32,address,address,address)"(
      _name: Arrayish,
      _type: Arrayish,
      _owner: string,
      _oracle: string,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
     * Initializes the contract setting the deployer as the initial owner.
     */
    "initialize(address)"(
      sender: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferForward(
      _symbol: Arrayish,
      _forwarder: string,
      _sender: string,
      _receiver: string,
      _tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferForward(bytes32,address,address,address,uint256)"(
      _symbol: Arrayish,
      _forwarder: string,
      _sender: string,
      _receiver: string,
      _tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      owner: string,
      buyer: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      owner: string,
      buyer: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256,address,bytes32)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      forwarder: string,
      bondSymbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    requestIssue(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "requestIssue(bytes16,address,bytes32,address)"(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    convert(
      txId: Arrayish,
      result: Arrayish,
      rtype: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "convert(bytes32,bytes16,bytes32)"(
      txId: Arrayish,
      result: Arrayish,
      rtype: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  name(overrides?: TransactionOverrides): Promise<string>;

  "name()"(overrides?: TransactionOverrides): Promise<string>;

  approve(
    spender: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

  balances(arg0: string, overrides?: TransactionOverrides): Promise<string>;

  "balances(address)"(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  decimals(overrides?: TransactionOverrides): Promise<number>;

  "decimals()"(overrides?: TransactionOverrides): Promise<number>;

  issues(
    arg0: string,
    arg1: string,
    overrides?: TransactionOverrides
  ): Promise<{
    parValue: string;
    price: string;
    purchasedIssueAmount: string;
    paidInAmount: string;
    paidInCurrency: string;
    timeIssuedOrSubscribed: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
  }>;

  "issues(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: TransactionOverrides
  ): Promise<{
    parValue: string;
    price: string;
    purchasedIssueAmount: string;
    paidInAmount: string;
    paidInCurrency: string;
    timeIssuedOrSubscribed: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
  }>;

  purchases(
    arg0: string,
    arg1: string,
    overrides?: TransactionOverrides
  ): Promise<{
    parValue: string;
    price: string;
    purchasedIssueAmount: string;
    paidInAmount: string;
    paidInCurrency: string;
    timeIssuedOrSubscribed: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
  }>;

  "purchases(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: TransactionOverrides
  ): Promise<{
    parValue: string;
    price: string;
    purchasedIssueAmount: string;
    paidInAmount: string;
    paidInCurrency: string;
    timeIssuedOrSubscribed: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
  }>;

  balanceOf(
    tokenOwner: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "balanceOf(address)"(
    tokenOwner: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
  renounceOwnership(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
  "renounceOwnership()"(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  bondName(overrides?: TransactionOverrides): Promise<string>;

  "bondName()"(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  "owner()"(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns true if the caller is the current owner.
   */
  isOwner(overrides?: TransactionOverrides): Promise<boolean>;

  /**
   * Returns true if the caller is the current owner.
   */
  "isOwner()"(overrides?: TransactionOverrides): Promise<boolean>;

  symbol(overrides?: TransactionOverrides): Promise<string>;

  "symbol()"(overrides?: TransactionOverrides): Promise<string>;

  transfer(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  allowance(
    tokenOwner: string,
    spender: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    tokenOwner: string,
    spender: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
  transferOwnership(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  initialize(
    _name: Arrayish,
    _type: Arrayish,
    _owner: string,
    _oracle: string,
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "initialize(bytes32,bytes32,address,address,address)"(
    _name: Arrayish,
    _type: Arrayish,
    _owner: string,
    _oracle: string,
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
   * Initializes the contract setting the deployer as the initial owner.
   */
  "initialize(address)"(
    sender: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferForward(
    _symbol: Arrayish,
    _forwarder: string,
    _sender: string,
    _receiver: string,
    _tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferForward(bytes32,address,address,address,uint256)"(
    _symbol: Arrayish,
    _forwarder: string,
    _sender: string,
    _receiver: string,
    _tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    owner: string,
    buyer: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    owner: string,
    buyer: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256,address,bytes32)"(
    sender: string,
    receiver: string,
    tokens: BigNumberish,
    forwarder: string,
    bondSymbol: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  requestIssue(
    amount: Arrayish,
    payer: string,
    currency: Arrayish,
    cashContract: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "requestIssue(bytes16,address,bytes32,address)"(
    amount: Arrayish,
    payer: string,
    currency: Arrayish,
    cashContract: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  convert(
    txId: Arrayish,
    result: Arrayish,
    rtype: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "convert(bytes32,bytes16,bytes32)"(
    txId: Arrayish,
    result: Arrayish,
    rtype: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    ViaBondIssued(
      token: null,
      currency: null,
      value: null,
      price: null,
      tenure: null
    ): EventFilter;

    ViaBondRedeemed(
      currency: null,
      value: null,
      price: null,
      tenure: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Approval(
      tokenOwner: string | null,
      spender: string | null,
      tokens: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, tokens: null): EventFilter;
  };

  estimate: {
    name(overrides?: TransactionOverrides): Promise<BigNumber>;

    "name()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    approve(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    balances(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: TransactionOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    issues(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "issues(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    purchases(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "purchases(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    balanceOf(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    renounceOwnership(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    "renounceOwnership()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    bondName(overrides?: TransactionOverrides): Promise<BigNumber>;

    "bondName()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns true if the caller is the current owner.
     */
    "isOwner()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    symbol(overrides?: TransactionOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    transfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    allowance(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    initialize(
      _name: Arrayish,
      _type: Arrayish,
      _owner: string,
      _oracle: string,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "initialize(bytes32,bytes32,address,address,address)"(
      _name: Arrayish,
      _type: Arrayish,
      _owner: string,
      _oracle: string,
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Initializes the contract setting the deployer as the initial owner.
     */
    "initialize(address)"(
      sender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    transferForward(
      _symbol: Arrayish,
      _forwarder: string,
      _sender: string,
      _receiver: string,
      _tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferForward(bytes32,address,address,address,uint256)"(
      _symbol: Arrayish,
      _forwarder: string,
      _sender: string,
      _receiver: string,
      _tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    transferFrom(
      owner: string,
      buyer: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      owner: string,
      buyer: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256,address,bytes32)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      forwarder: string,
      bondSymbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    requestIssue(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "requestIssue(bytes16,address,bytes32,address)"(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    convert(
      txId: Arrayish,
      result: Arrayish,
      rtype: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "convert(bytes32,bytes16,bytes32)"(
      txId: Arrayish,
      result: Arrayish,
      rtype: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
