/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription,
} from ".";

interface OracleAddrResolverIInterface extends Interface {
  functions: {
    getAddress: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class OracleAddrResolverI extends Contract {
  connect(signerOrProvider: Signer | Provider | string): OracleAddrResolverI;
  attach(addressOrName: string): OracleAddrResolverI;
  deployed(): Promise<OracleAddrResolverI>;

  on(event: EventFilter | string, listener: Listener): OracleAddrResolverI;
  once(event: EventFilter | string, listener: Listener): OracleAddrResolverI;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): OracleAddrResolverI;
  removeAllListeners(eventName: EventFilter | string): OracleAddrResolverI;
  removeListener(eventName: any, listener: Listener): OracleAddrResolverI;

  interface: OracleAddrResolverIInterface;

  functions: {
    getAddress(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    "getAddress()"(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  getAddress(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  "getAddress()"(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    getAddress(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getAddress()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
