/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription,
} from ".";

interface SolcCheckerInterface extends Interface {
  functions: {
    f: TypedFunctionDescription<{ encode([x]: [Arrayish]): string }>;
  };

  events: {};
}

export class SolcChecker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): SolcChecker;
  attach(addressOrName: string): SolcChecker;
  deployed(): Promise<SolcChecker>;

  on(event: EventFilter | string, listener: Listener): SolcChecker;
  once(event: EventFilter | string, listener: Listener): SolcChecker;
  addListener(eventName: EventFilter | string, listener: Listener): SolcChecker;
  removeAllListeners(eventName: EventFilter | string): SolcChecker;
  removeListener(eventName: any, listener: Listener): SolcChecker;

  interface: SolcCheckerInterface;

  functions: {
    f(
      x: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "f(bytes)"(
      x: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  f(
    x: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "f(bytes)"(
    x: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    f(x: Arrayish, overrides?: TransactionOverrides): Promise<BigNumber>;

    "f(bytes)"(
      x: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
