/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription,
} from ".";

interface TokenInterface extends Interface {
  functions: {
    name: TypedFunctionDescription<{ encode([]: []): string }>;

    approve: TypedFunctionDescription<{
      encode([spender, tokens]: [string, BigNumberish]): string;
    }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    balances: TypedFunctionDescription<{ encode([]: [string]): string }>;

    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    balanceOf: TypedFunctionDescription<{
      encode([tokenOwner]: [string]): string;
    }>;

    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    tokenSymbol: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;

    transfer: TypedFunctionDescription<{
      encode([receiver, tokens]: [string, BigNumberish]): string;
    }>;

    product: TypedFunctionDescription<{ encode([]: []): string }>;

    allowance: TypedFunctionDescription<{
      encode([tokenOwner, spender]: [string, string]): string;
    }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;

    initialize: TypedFunctionDescription<{
      encode([_factory, _name, _owner, _product, _symbol]: [
        string,
        Arrayish,
        string,
        Arrayish,
        Arrayish
      ]): string;
    }>;

    addTotalSupply: TypedFunctionDescription<{
      encode([amount]: [Arrayish]): string;
    }>;

    reduceSupply: TypedFunctionDescription<{
      encode([amount]: [Arrayish]): string;
    }>;

    addBalance: TypedFunctionDescription<{
      encode([party, amount]: [string, Arrayish]): string;
    }>;

    reduceBalance: TypedFunctionDescription<{
      encode([party, amount]: [string, Arrayish]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([sender, receiver, tokens]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    transferToken: TypedFunctionDescription<{
      encode([sender, receiver, tokens]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    requestTransfer: TypedFunctionDescription<{
      encode([receiver, tokens]: [string, BigNumberish]): string;
    }>;

    requestIssue: TypedFunctionDescription<{
      encode([amount, payer, currency, cashContract]: [
        Arrayish,
        string,
        Arrayish,
        string
      ]): string;
    }>;
  };

  events: {
    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;

    Approval: TypedEventDescription<{
      encodeTopics([tokenOwner, spender, tokens]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    Transfer: TypedEventDescription<{
      encodeTopics([from, to, tokens]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;
  };
}

export class Token extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Token;
  attach(addressOrName: string): Token;
  deployed(): Promise<Token>;

  on(event: EventFilter | string, listener: Listener): Token;
  once(event: EventFilter | string, listener: Listener): Token;
  addListener(eventName: EventFilter | string, listener: Listener): Token;
  removeAllListeners(eventName: EventFilter | string): Token;
  removeListener(eventName: any, listener: Listener): Token;

  interface: TokenInterface;

  functions: {
    name(overrides?: TransactionOverrides): Promise<string>;

    "name()"(overrides?: TransactionOverrides): Promise<string>;

    approve(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    balances(arg0: string, overrides?: TransactionOverrides): Promise<string>;

    "balances(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    decimals(overrides?: TransactionOverrides): Promise<number>;

    "decimals()"(overrides?: TransactionOverrides): Promise<number>;

    balanceOf(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    "renounceOwnership()"(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenSymbol(overrides?: TransactionOverrides): Promise<string>;

    "tokenSymbol()"(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: TransactionOverrides): Promise<boolean>;

    /**
     * Returns true if the caller is the current owner.
     */
    "isOwner()"(overrides?: TransactionOverrides): Promise<boolean>;

    symbol(overrides?: TransactionOverrides): Promise<string>;

    "symbol()"(overrides?: TransactionOverrides): Promise<string>;

    transfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    product(overrides?: TransactionOverrides): Promise<string>;

    "product()"(overrides?: TransactionOverrides): Promise<string>;

    allowance(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    initialize(
      _factory: string,
      _name: Arrayish,
      _owner: string,
      _product: Arrayish,
      _symbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "initialize(address,bytes32,address,bytes32,bytes32)"(
      _factory: string,
      _name: Arrayish,
      _owner: string,
      _product: Arrayish,
      _symbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
     * Initializes the contract setting the deployer as the initial owner.
     */
    "initialize(address)"(
      sender: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    addTotalSupply(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "addTotalSupply(bytes16)"(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    reduceSupply(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "reduceSupply(bytes16)"(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    addBalance(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "addBalance(address,bytes16)"(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    reduceBalance(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "reduceBalance(address,bytes16)"(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferToken(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferToken(address,address,uint256)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    requestTransfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "requestTransfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    requestIssue(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "requestIssue(bytes16,address,bytes32,address)"(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  name(overrides?: TransactionOverrides): Promise<string>;

  "name()"(overrides?: TransactionOverrides): Promise<string>;

  approve(
    spender: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

  balances(arg0: string, overrides?: TransactionOverrides): Promise<string>;

  "balances(address)"(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  decimals(overrides?: TransactionOverrides): Promise<number>;

  "decimals()"(overrides?: TransactionOverrides): Promise<number>;

  balanceOf(
    tokenOwner: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "balanceOf(address)"(
    tokenOwner: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
  renounceOwnership(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
  "renounceOwnership()"(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenSymbol(overrides?: TransactionOverrides): Promise<string>;

  "tokenSymbol()"(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  "owner()"(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns true if the caller is the current owner.
   */
  isOwner(overrides?: TransactionOverrides): Promise<boolean>;

  /**
   * Returns true if the caller is the current owner.
   */
  "isOwner()"(overrides?: TransactionOverrides): Promise<boolean>;

  symbol(overrides?: TransactionOverrides): Promise<string>;

  "symbol()"(overrides?: TransactionOverrides): Promise<string>;

  transfer(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  product(overrides?: TransactionOverrides): Promise<string>;

  "product()"(overrides?: TransactionOverrides): Promise<string>;

  allowance(
    tokenOwner: string,
    spender: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    tokenOwner: string,
    spender: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
  transferOwnership(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  initialize(
    _factory: string,
    _name: Arrayish,
    _owner: string,
    _product: Arrayish,
    _symbol: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "initialize(address,bytes32,address,bytes32,bytes32)"(
    _factory: string,
    _name: Arrayish,
    _owner: string,
    _product: Arrayish,
    _symbol: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
   * Initializes the contract setting the deployer as the initial owner.
   */
  "initialize(address)"(
    sender: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  addTotalSupply(
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "addTotalSupply(bytes16)"(
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  reduceSupply(
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "reduceSupply(bytes16)"(
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  addBalance(
    party: string,
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "addBalance(address,bytes16)"(
    party: string,
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  reduceBalance(
    party: string,
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "reduceBalance(address,bytes16)"(
    party: string,
    amount: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    sender: string,
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferToken(
    sender: string,
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferToken(address,address,uint256)"(
    sender: string,
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  requestTransfer(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "requestTransfer(address,uint256)"(
    receiver: string,
    tokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  requestIssue(
    amount: Arrayish,
    payer: string,
    currency: Arrayish,
    cashContract: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "requestIssue(bytes16,address,bytes32,address)"(
    amount: Arrayish,
    payer: string,
    currency: Arrayish,
    cashContract: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Approval(
      tokenOwner: string | null,
      spender: string | null,
      tokens: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, tokens: null): EventFilter;
  };

  estimate: {
    name(overrides?: TransactionOverrides): Promise<BigNumber>;

    "name()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    approve(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: TransactionOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    balances(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: TransactionOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    balanceOf(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      tokenOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    renounceOwnership(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
 * Leaves the contract without owner. It will not be possible to call
 `onlyOwner` functions anymore. Can only be called by the current owner.
      * > Note: Renouncing ownership will leave the contract without an owner,
 thereby removing any functionality that is only available to the owner.
 */
    "renounceOwnership()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    tokenSymbol(overrides?: TransactionOverrides): Promise<BigNumber>;

    "tokenSymbol()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    "owner()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns true if the caller is the current owner.
     */
    "isOwner()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    symbol(overrides?: TransactionOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    transfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    product(overrides?: TransactionOverrides): Promise<BigNumber>;

    "product()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    allowance(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      tokenOwner: string,
      spender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
 * Transfers ownership of the contract to a new account (`newOwner`).
 Can only be called by the current owner.
 */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    initialize(
      _factory: string,
      _name: Arrayish,
      _owner: string,
      _product: Arrayish,
      _symbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "initialize(address,bytes32,address,bytes32,bytes32)"(
      _factory: string,
      _name: Arrayish,
      _owner: string,
      _product: Arrayish,
      _symbol: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Initializes the contract setting the deployer as the initial owner.
     */
    "initialize(address)"(
      sender: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    addTotalSupply(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "addTotalSupply(bytes16)"(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    reduceSupply(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "reduceSupply(bytes16)"(
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    addBalance(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "addBalance(address,bytes16)"(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    reduceBalance(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "reduceBalance(address,bytes16)"(
      party: string,
      amount: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    transferFrom(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    transferToken(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferToken(address,address,uint256)"(
      sender: string,
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    requestTransfer(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "requestTransfer(address,uint256)"(
      receiver: string,
      tokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    requestIssue(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "requestIssue(bytes16,address,bytes32,address)"(
      amount: Arrayish,
      payer: string,
      currency: Arrayish,
      cashContract: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
